# Dockerfile-backend
FROM openjdk:17-jdk-slim

MAINTAINER oblivionLi (Liviu G. Andrei = liviuandrei.dev@gmail.com)

VOLUME /tmp

WORKDIR /app

COPY gradlew .
COPY gradle gradle
COPY build.gradle settings.gradle ./
COPY src src

RUN ./gradlew --no-daemon build

COPY build/libs/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]